# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\PSI\ToysnSamples\PythonPlayground\SuperSimpleGui\SuperSimpleMainWindow.ui',
# licensing of 'c:\PSI\ToysnSamples\PythonPlayground\SuperSimpleGui\SuperSimpleMainWindow.ui' applies.
#
# Created: Tue Sep  3 16:14:37 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSimpleGui = QtWidgets.QWidget()
        self.tabSimpleGui.setObjectName("tabSimpleGui")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabSimpleGui)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.tabSimpleGui)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.lblItemCount = QtWidgets.QLabel(self.tabSimpleGui)
        self.lblItemCount.setObjectName("lblItemCount")
        self.verticalLayout_2.addWidget(self.lblItemCount)
        self.btnBrowse = QtWidgets.QPushButton(self.tabSimpleGui)
        self.btnBrowse.setObjectName("btnBrowse")
        self.verticalLayout_2.addWidget(self.btnBrowse)
        self.btnOpenDiffForm = QtWidgets.QPushButton(self.tabSimpleGui)
        self.btnOpenDiffForm.setObjectName("btnOpenDiffForm")
        self.verticalLayout_2.addWidget(self.btnOpenDiffForm)
        self.tabWidget.addTab(self.tabSimpleGui, "")
        self.tabCosineList = QtWidgets.QWidget()
        self.tabCosineList.setObjectName("tabCosineList")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabCosineList)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cosListView = QtWidgets.QListView(self.tabCosineList)
        self.cosListView.setViewMode(QtWidgets.QListView.ListMode)
        self.cosListView.setObjectName("cosListView")
        self.verticalLayout_5.addWidget(self.cosListView)
        self.groupBox = QtWidgets.QGroupBox(self.tabCosineList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radRadians = QtWidgets.QRadioButton(self.groupBox)
        self.radRadians.setChecked(True)
        self.radRadians.setObjectName("radRadians")
        self.horizontalLayout.addWidget(self.radRadians)
        self.radDegrees = QtWidgets.QRadioButton(self.groupBox)
        self.radDegrees.setObjectName("radDegrees")
        self.horizontalLayout.addWidget(self.radDegrees)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.widget = QtWidgets.QWidget(self.tabCosineList)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinRangeMax = QtWidgets.QDoubleSpinBox(self.widget)
        self.spinRangeMax.setObjectName("spinRangeMax")
        self.gridLayout.addWidget(self.spinRangeMax, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.spinRangeMin = QtWidgets.QDoubleSpinBox(self.widget)
        self.spinRangeMin.setObjectName("spinRangeMin")
        self.gridLayout.addWidget(self.spinRangeMin, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.spinCountStep = QtWidgets.QDoubleSpinBox(self.widget)
        self.spinCountStep.setDecimals(0)
        self.spinCountStep.setProperty("value", 3.0)
        self.spinCountStep.setObjectName("spinCountStep")
        self.gridLayout.addWidget(self.spinCountStep, 2, 0, 1, 1)
        self.lblCountStep = QtWidgets.QLabel(self.widget)
        self.lblCountStep.setObjectName("lblCountStep")
        self.gridLayout.addWidget(self.lblCountStep, 2, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.widget)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabCosineList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radSteps = QtWidgets.QRadioButton(self.groupBox_3)
        self.radSteps.setObjectName("radSteps")
        self.verticalLayout_3.addWidget(self.radSteps)
        self.radCounts = QtWidgets.QRadioButton(self.groupBox_3)
        self.radCounts.setChecked(True)
        self.radCounts.setObjectName("radCounts")
        self.verticalLayout_3.addWidget(self.radCounts)
        self.chkClosedInterval = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkClosedInterval.setObjectName("chkClosedInterval")
        self.verticalLayout_3.addWidget(self.chkClosedInterval)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.btnCalculate = QtWidgets.QPushButton(self.tabCosineList)
        self.btnCalculate.setObjectName("btnCalculate")
        self.verticalLayout_5.addWidget(self.btnCalculate)
        self.tabWidget.addTab(self.tabCosineList, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lblItemCount.setText(QtWidgets.QApplication.translate("MainWindow", "Items: 0", None, -1))
        self.btnBrowse.setText(QtWidgets.QApplication.translate("MainWindow", "Pick a folder", None, -1))
        self.btnOpenDiffForm.setText(QtWidgets.QApplication.translate("MainWindow", "Open a Different Form", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSimpleGui), QtWidgets.QApplication.translate("MainWindow", "SimpleGui", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Angle Units", None, -1))
        self.radRadians.setText(QtWidgets.QApplication.translate("MainWindow", "Radians", None, -1))
        self.radDegrees.setText(QtWidgets.QApplication.translate("MainWindow", "Degrees", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Range Max", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Range Min", None, -1))
        self.lblCountStep.setText(QtWidgets.QApplication.translate("MainWindow", "Counts", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Range Definition Method", None, -1))
        self.radSteps.setText(QtWidgets.QApplication.translate("MainWindow", "Steps", None, -1))
        self.radCounts.setText(QtWidgets.QApplication.translate("MainWindow", "Counts", None, -1))
        self.chkClosedInterval.setText(QtWidgets.QApplication.translate("MainWindow", "Closed Interval", None, -1))
        self.btnCalculate.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate Cosines", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCosineList), QtWidgets.QApplication.translate("MainWindow", "CosineList", None, -1))


